name: Auto Update Google Trends

on:
  schedule:
    - cron: '0 5 * * 1'  # Every Monday at 5am UTC
  workflow_dispatch:

jobs:
  update-trends:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytrends plotly pandas

      - name: Run script to update trends.csv
        run: python google_rtt.py

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push updated trends.csv
        run: |
          git add trends.csv
          git commit -m "Auto-update trends.csv" || echo "No changes to commit"
          git push