name: Update Trends CSV Weekly

on:
  schedule:
    - cron: "0 12 * * 1"  # Every Monday at 12:00 UTC
  workflow_dispatch:

jobs:
  update-trends:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies inline
      run: |
        pip install pytrends pandas plotly

    - name: Run trend scraper
      run: python google_rtt.py

    - name: Commit and push updated trends.csv
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add trends.csv
        git commit -m "Auto-update trends.csv [skip ci]" || echo "No changes to commit"
        git push

